# Form implementation generated from reading ui file 'c:\Users\syaun\OneDrive\Desktop\AIP2020\ui6\noise.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(712, 499)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lb_preview = QtWidgets.QLabel(parent=self.centralwidget)
        self.lb_preview.setGeometry(QtCore.QRect(130, 30, 431, 321))
        self.lb_preview.setObjectName("lb_preview")
        self.slider_mean = QtWidgets.QSlider(parent=self.centralwidget)
        self.slider_mean.setGeometry(QtCore.QRect(260, 380, 160, 22))
        self.slider_mean.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.slider_mean.setObjectName("slider_mean")
        self.slider_sigma = QtWidgets.QSlider(parent=self.centralwidget)
        self.slider_sigma.setGeometry(QtCore.QRect(260, 420, 160, 22))
        self.slider_sigma.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.slider_sigma.setObjectName("slider_sigma")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(180, 380, 47, 12))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(180, 420, 47, 12))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lb_num_show = QtWidgets.QLabel(parent=self.centralwidget)
        self.lb_num_show.setGeometry(QtCore.QRect(450, 380, 111, 61))
        self.lb_num_show.setObjectName("lb_num_show")
        self.btn_confirm = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_confirm.setGeometry(QtCore.QRect(600, 420, 75, 31))
        self.btn_confirm.setObjectName("btn_confirm")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 712, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lb_preview.setText(_translate("MainWindow", "TextLabel"))
        self.label_2.setText(_translate("MainWindow", "mean"))
        self.label_3.setText(_translate("MainWindow", "sigma"))
        self.lb_num_show.setText(_translate("MainWindow", "TextLabel"))
        self.btn_confirm.setText(_translate("MainWindow", "Confirm"))
