# Form implementation generated from reading ui file 'c:\Users\syaun\OneDrive\桌面\cropper_ui\AIP2020\ui6\pyui.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(40, 50, 471, 221))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lb_input = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.lb_input.setObjectName("lb_input")
        self.horizontalLayout.addWidget(self.lb_input)
        self.lb_output = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.lb_output.setObjectName("lb_output")
        self.horizontalLayout.addWidget(self.lb_output)
        self.btn_select_img = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_select_img.setGeometry(QtCore.QRect(590, 70, 75, 23))
        self.btn_select_img.setObjectName("btn_select_img")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lb_input.setText(_translate("MainWindow", "TextLabel"))
        self.lb_output.setText(_translate("MainWindow", "TextLabel"))
        self.btn_select_img.setText(_translate("MainWindow", "PushButton"))
