# Form implementation generated from reading ui file 'c:\Users\kuen\Documents\GitHub\AIP2020\ui6\Edge_mask_pyui.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(586, 431)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.cb_select = QtWidgets.QComboBox(parent=self.centralwidget)
        self.cb_select.setGeometry(QtCore.QRect(40, 20, 121, 21))
        self.cb_select.setObjectName("cb_select")
        self.cb_select.addItem("")
        self.cb_select.addItem("")
        self.cb_select.addItem("")
        self.cb_select.addItem("")
        self.cb_select.addItem("")
        self.tv_mask = QtWidgets.QTableView(parent=self.centralwidget)
        self.tv_mask.setGeometry(QtCore.QRect(30, 70, 256, 192))
        self.tv_mask.setObjectName("tv_mask")
        self.btn_confirm = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_confirm.setGeometry(QtCore.QRect(380, 360, 75, 23))
        self.btn_confirm.setObjectName("btn_confirm")
        self.btn_close = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_close.setGeometry(QtCore.QRect(470, 360, 75, 23))
        self.btn_close.setObjectName("btn_close")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 586, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Edge detection mask"))
        self.cb_select.setItemText(0, _translate("MainWindow", "快速選擇模板"))
        self.cb_select.setItemText(1, _translate("MainWindow", "Sobal (x-axis 3x3)"))
        self.cb_select.setItemText(2, _translate("MainWindow", "Sobal (y-axis 3x3)"))
        self.cb_select.setItemText(3, _translate("MainWindow", "Scharr (x-axis 3x3)"))
        self.cb_select.setItemText(4, _translate("MainWindow", "Scharr (y-axis 3x3)"))
        self.btn_confirm.setText(_translate("MainWindow", "Confirm"))
        self.btn_close.setText(_translate("MainWindow", "Cancel"))
